import React, { createContext, useState } from 'react'
export const Createcontext = createContext();
export const Provider = (props) => {
    const [data, setData] = useState([{
        "Id": "1",
        "imageurl":"https://kubrick.htvapps.com/htv-prod-media.s3.amazonaws.com/images/golden-globes-1483816829.jpg?crop=1.00xw:0.752xh;0,0.0414xh&resize=1200:*",
        "title":"Golden Globe Awards",
        "description":"The Golden Globe Awards are accolades bestowed by the 87 members of the Hollywood Foreign Press Association beginning in January 1944, recognizing excellence in both American and international film and television.",
        "category": "Hollywood",
        "date":"Jan 10 2022",
        "likes":"10",
        "details":"The Golden Globes awards ceremony began in 1944. Members of the Hollywood Foreign Press Association present awards for achievement in film and television.The Power of the Dog is a 2021 Western psychological drama film[6][7][8] written and directed by Jane Campion, based on the 1967 novel of the same name by Thomas Savage. The film stars Benedict Cumberbatch, Kirsten Dunst, Jesse Plemons, and Kodi Smit-McPhee. Shot mostly across rural Otago, New Zealand, the film is an international co-production among New Zealand, Australia, the United Kingdom, and Canada. The film deals with themes such as love, grief, resentment, jealousy and sexuality.[9].It also received seven nominations at the 79th Golden Globe Awards, winning Best Motion Picture – Drama, Best Supporting Actor – Motion Picture for Smit-McPhee and Best Director for Campion and ten nominations at the 27th Critics' Choice Awards, including Best Picture.",
        "detailsimage":"https://img.jagranjosh.com/images/2022/January/1012022/Untitled%20design%20(1).jpg",
        "detailsimage":"https://img.jagranjosh.com/images/2022/January/1012022/Untitled%20design%20(1).jpg  ",
        "content":" click here to know more",
    },
    {

        "Id": "2",
        "imageurl":"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcShoWb4WDDvS4t6tZ13tOJ-zdnrJiIoB4yTswLx8gLjZTuYwPte",
        "title":"Brahmāstra",
        "description":"Brahmāstra, is an upcoming Indian Hindi-language superhero film written and directed by Ayan Mukerji, and produced by Karan Johar. It stars Amitabh Bachchan, Ranbir Kapoor, Alia Bhatt, Mouni Roy and Nagarjuna Akkineni",
        "category": "Bollywood",
        "date":"December 16 2021",
        "likes":"10",
        "details":"BRAHMASTRA - the Trilogy, is a 3-part film franchise and the beginning of India's first original universe - the Astraverse. It is a new original cinematic universe inspired by deeply rooted concepts and tales in Indian mythology but set in the modern world, with epic storytelling of fantasy, adventure, good vs evil, love and hope; all told using cutting edge technology and never-seen-before visual spectacles.",
        "detailsimage":"https://imageory.clapnumber.com/albums/large/aaadum_1570386312_poster_0.jpg",
    },
    {
        "Id": "3",
        "imageurl":"https://cdn.geekwire.com/wp-content/uploads/2021/10/Meta_lockup_primary_RGB-630x307.jpg",
        "title":"META",
        "description":"The future of the internet is going to be virtual and Meta the company known to the public as Facebook says, believing that 1 billion people will be working and playing in the immersive, three-dimensional world referred to as the Metaverse by the end of the decade.",
        "category": "Technology",
        "date":"December 24 2022",
        "likes":"10",
        "details":"Meta is a prefix — a word put before another — that means after or or beyond, to operate at a higher level, or change. For example, metacarpus (the finger bones after the wrist), metalanguage (language used to describe another language) and metamorphosis (a change of form).Facebook announced that they were rebranding. Just a few weeks later, Zuckerberg then announced Facebook's new name would be Meta, inspired by the Greek word meaning beyond and their plan to created a next-gen metaverse internet.",
        "detailsimage":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQg31GuBTLuOFUIULy3qS8lLCv08HNzv083lQ&usqp=CAU",
    },
    {
        "Id": "4",
        "imageurl":"https://pravase.co.in/admin_pravase/uploads/yatradham/Srisailam-Yatradham_1603345052.JPG",
        "title":"Srisailam",
        "description":"Srisailam is one of the popular tourist destinations in Andhra Pradesh and considered one of the most important pilgrimage centres of Lord Shiva.",
        "category": "Travel",
        "date":"December 24 2022",
        "likes":"10",
        "details":"It is located at 180Kms from Kurnool and 210 Kms from Hyderabad an attitude of over 1500 ft. above the Sea level in the picturesque natural environment in the Northern most part of the Nallamalas hill range. The temple at Srisailam is the ancient and sacred place of South India. The presiding deity of the place is Brahmaramba Mallikarjuna Swamy in natural stone formations in the shape of Lingam and is listed as one of the twelve Jyotirlingams existing in the country. The Temple built in 14th Century and the walls are carved with depictions of elephants hunting scenes and Lord Shiva in different manifestations. Apart from the main temple there are other places like Sikhareswaram, the gates of Heaven, Hatakeswaram and PalaDhara  PanchaDhara, Sakshi Ganapathi, Sivaji spurthikendra, Pathala Ganga, Chenchu Lakshmi Tribal Museum & Rajeev Gandhi Wild life sanctuary etc. are well worth for visit.",
        "detailsimage":"https://static2.tripoto.com/media/filter/tst/img/292917/TripDocument/1541089680_maxresdefault_1.jpg",
    },
    {
        "Id": "5",
        "imageurl":"https://previews.123rf.com/images/snapgalleria/snapgalleria1902/snapgalleria190200005/117399411-illustration-of-delicious-traditional-food-of-andhra-pradesh-india.jpg",
        "title":"Delicious traditional food of Andhra Pradesh",
        "description":"What to Eat in Andhra Pradesh · 1. Hyderabadi Biriyani · 2. Kaleem · 3. Pesarattu · 4. Chilly Bajji · 5. Ulava Charu · 6. Maamsam Koora · 7. Bommidala Pulusu ·",
        "category": "Food",
        "date":"December 24 2020",
        "likes":"10",
        "details":"The state that gave a whole new definition and taste to Biryani is famous for giving birth to some of the most palatable Biryani and Pulao recipes. The original mouth-watering Andhra Chicken Biryani uses a rich combination of aromatic herbs and spices to give the long thin rice grains, a succulent taste. Tossed vegetables are mixed with Chicken to bring the taste it is best known for. Try the Andhra Chicken Biryani for your lunch to have a juicy fulfilling experience.",
        "detailsimage":"https://www.holidify.com/images/cmsuploads/compressed/andhra_20191112141755.jpg",
    },
    {
        "Id": "6",
        "imageurl":"https://img.traveltriangle.com/blog/wp-content/uploads/2020/03/Picnic-spots-near-Tirupati.jpg",
        "title":"TIRUPATI",
        "description":"Tirupati is a city in the Indian state of Andhra Pradesh. Its Sri Venkateswara Temple sits atop one of the the 7 peaks of Tirumala Hills, attracting scores of Hindu pilgrims.",
        "category": "Travel",
        "date":"December 04 2021",
        "likes":"10",
        "details":"Tirupati Balaji temple is the most popular temple on the earth today inviting the maximum number of devotes on any given day and attracting the largest amount of donations from them on a daily basis. Devotees pray the Lord to fulfill their wishes and upon their wishes getting fulfilled, it is a customary practice to offer their donations at the temple Hundi. In this manner lakhs of devotees pour into the temple to make their contributions.",
        "detailsimage":"https://static.toiimg.com/thumb/msid-87752765,width-1200,height-900,resizemode-4/.jpg",
    },
    {
        "Id": "7",
        "imageurl":"https://images.newscientist.com/wp-content/uploads/2021/12/14131831/PRI_212734844.jpg?width=800",
        "title":"Space tourism",
        "description":"A flurry of short flights aboard privately funded craft saw space tourism begin with a bang for billionaires in 2021.",
        "category": "Technology",
        "date":"December 15 2021",
        "likes":"10",
        "details":"Three different commercial ventures carried ultra-rich passengers into space in 2021. It began with Richard Branson, who took a 90-minute suborbital flight aboard his Virgin Galactic space plane, SpaceShipTwo, on 11 July. Whether or not the flight counts as having gone to space, though, remains a contentious subject  the US government defines space as beginning 50 miles (or just over 80 kilometres) up, which was the altitude of Bransons flight, but the internationally held definition of space, the Kármán line, is 100 kilometres above Earth.Following the US government definition, Branson was the first person to visit space on a spacecraft made by his own company. Amazon founder Jeff Bezos came a close second on 20 July, when he rode his firm Blue Origins New Shepard rocket on a suborbital flight past the Kármán line. While he reached a higher altitude than Branson at 107 km, the flight was shorter at 11 minutes, including 3 minutes of weightlessness. New Shepard flew again on 12 October with new passengers, including Star Trek actor William Shatner.",
        "detailsimage":"https://images.newscientist.com/wp-content/uploads/2021/12/14131830/PRI_212735243.jpg?width=800",
    },
    {
    "Id": "8",
        "imageurl":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiAjSq2LACshpvxVl1jDIwh6_T1WleBdCKyw&usqp=CAU",
        "title":"Dangal",
        "description":"Highest-grossing Indian film",
        "category": "Bollywood",
        "date":"December 24 2016",
        "likes":"10",
        "details":"Dangal is loosely based on the Phogat family in Haryana. According to Mans World India, Mahavir Singh trained under Chandgi Ram, a Padma Shri winner, in Delhi after which he became a successful mercenary wrestler and won numerous dangals in various villages of Himachal, Uttar Pradesh, Punjab, and other states. Mahavir decided to train his daughters in the year 2000 when Indian weightlifter Karnam Malaeshwari became the first Indian woman to win an Olympic medal. He trained his daughters in a sport that was traditionally male-dominated and in a state which was known for gender inequality and low sex ratio. Phogat quit his job at the Haryana State Electricity Board to give more time to his daughter’s training and the girls used to practice with the boys since there were no other girls who practiced this sport at the time. However, people did not let them fight at local dangals due to conservative views and he took them to the Sports Authority of India Centre in Sonipat where they trained further.",
        "detailsimage":"https://m.media-amazon.com/images/M/MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_.jpg",
    },
    {
    "Id": "9",
        "imageurl":"https://1.bp.blogspot.com/-Yf9CV59_UfU/XyKfWeW6ToI/AAAAAAAAcP8/giR_Dkc95OgHyha42N5nsm2Ic8cYUxaugCLcBGAsYHQ/s1600/SpiderMan%2BImages%2B%2B%25281%2529.png",
        "title":"SpiderMan",
        "description":"Spider-Man is a superhero appearing in American comic books published by Marvel Comics. Created by writer-editor Stan Lee and artist Steve Ditko",
        "category": "Hollywood",
        "date":"December 14 2021",
        "likes":"10",
        "details":"There have been nine Spider-Man movies since 2002: but which Spider-Man movie is best? Marvel's web-slinger is one of the most popular movie properties today, but it took a long time for Hollywood to realize how lucrative he could be. Until relatively recently, the wall-crawler had only ever journeyed to the small screen. He was the star of several series and TV films starring Nicholas Hammond, along with various acclaimed cartoons, such as the Spider-Man: The Animated Series. Although that isn’t to say that no one was trying to bring Spider-Man to the big screen.",
        "detailsimage":"https://1.bp.blogspot.com/-Yf9CV59_UfU/XyKfWeW6ToI/AAAAAAAAcP8/giR_Dkc95OgHyha42N5nsm2Ic8cYUxaugCLcBGAsYHQ/s1600/SpiderMan%2BImages%2B%2B%25281%2529.png",
    },
    {
    "Id": "10",
        "imageurl":"https://www.holidify.com/blog/wp-content/uploads/2016/08/Hyderabadi-Dum-Chicken-Biryani-5.jpg",
        "title":"Andhra Chicken Biryani",
        "description":"Andhra Chicken Biryani for your lunch to have a juicy fulfilling experience.",
        "category": "Food",
        "date":"December 04 2021",
        "likes":"10",
        "details":"The state that gave a whole new definition and taste to Biryani is famous for giving birth to some of the most palatable Biryani and Pulao recipes. The original mouth-watering Andhra Chicken Biryani uses a rich combination of aromatic herbs and spices to give the long thin rice grains, a succulent taste. Tossed vegetables are mixed with Chicken to bring the taste it is best known for. Try the Andhra Chicken Biryani for your lunch to have a juicy fulfilling experience.",
        "detailsimage":"https://www.holidify.com/blog/wp-content/uploads/2016/08/Hyderabadi-Dum-Chicken-Biryani-5.jpg",
    },
    {
    "Id": "11",
    "imageurl":"https://st1.bollywoodlife.com/wp-content/uploads/2017/05/Bahubali.jpg?impolicy=Medium_Widthonly&w=600",
    "title":"Bahubali",
    "description":"Both parts of Baahubali are essentially are fictional works, the epic movie series of director SS Rajamouli is inspired by several patches from the history of India.",
    "category": "Bollywood",
    "date":"April 04 2017",
    "likes":"10",
    "details":"The Kingdom of Mahishmati is ruled by queen Sivagami (Ramya) who is married to Bijjaladeva (Nassar). She takes charge of the kingdom when Amarendra Baahubali’s (Prabhas) mother passes away during labour. She takes care of Amarendra like her own son and ensures that he is brought up with the ability to rule the kingdom one day. Amarendra Baahubali also has a cousin brother Bhallala Deva (Rana Daggubati) who is Sivagami’s son by blood. With two sons and one kingdom to rule, Sivagami decides to test both her sons. She challenges them to win the upcoming war against the Kalakeyas and promises that whoever is victorious will be crowned the king.Though it was Bhallala Deva who kills the king of Kalakeyas, Sivagami announces Amarendra to be the winner of the challenge because of his leadership skills and his ability to empathise with his subjects. However, what happened after this to Amarendra Baahubali is a mystery. Except for the fact that the loyal lieutenant of Mahismati, Kattappa (Sathyaraj) killed Baahubali.He grows up to be a young man, who falls in love with Avanthika (Tamannaah). It is when he meets Avanthika, a rebellious warrior who is on a mission to save Devasena, that the secret of his life is revealed to him. Initially, he becomes a part of the mission to not lose Avanthika. However, when he is successful and frees Devasena from the clutches of Bhallala Deva, Kattappa follows him and comes to realise that Shivudu is, in fact, Amarendra’s son. ",
    "detailsimage":"https://kalingatv.com/wp-content/uploads/2017/10/Prabhas-Anushka-shetty.jpg",
},
{
    "Id": "12",
    "imageurl":"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/e93fe623-ec8b-43c0-ba62-8a3ce6f3a403/da6ivws-4832475a-472f-4627-931e-332c0655ef26.png",
    "title":"Bajrangi Bhaijaan",
    "description":"Pawan, a devotee of Lord Hanuman, finds a girl, who is speech impaired, lost in Haryana. He soon learns that she belongs to Pakistan and sets out to reunite her with her family at great personal cost.",
    "category": "Bollywood",
    "date":"July 17 2015",
    "likes":"10",
    "details":"A young mute girl from Pakistan loses herself in India with no way to head back. A devoted man with a magnanimous spirit undertakes the task to get her back to her motherland and unite her with her family.Salman Khan's Blockbuster Bajrangi Bhaijaan may be a work of fiction, but it is a real life story of a deaf and mute Indian girl stuck in Pakistan for 14 years.Bhaijaan is how a brother is called in Urdu with respect. Hence, Bajrangi Bhaijaan would mean 'Brother Bajrangi' where Bajrangi would be a name meaning strongly built and the name is spoken with respect. Edit. Report This. This is Salman Khan's second movie with Nawazuddin Siddique.Some scenes of the film were shot at Khan's Panvel farm house. Shooting also took place in the Kashmir Valley in places like Sonamarg and Zoji La. The film's climax was shot at Sonmarg near the Thajiwas glacier (at 10,000 ft above sea level) with around 7,000 people.Koduri Viswa Vijayendra Prasad is an Indian screenwriter and film director known for his works in Telugu, Tamil and Hindi cinema. In 2011, he directed the Telugu film Rajanna, which won the Nandi Award for Best Feature Film. He won Filmfare Award for Best Story in 2016 for the film Bajrangi Bhaijaan. ",
    "detailsimage":"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/e93fe623-ec8b-43c0-ba62-8a3ce6f3a403/da6ivws-4832475a-472f-4627-931e-332c0655ef26.png",
},
{
    "Id": "13",
    "imageurl":"https://e1.pngegg.com/pngimages/829/295/png-clipart-idiots-3-idiots-icon-thumbnail.png",
    "title":"3 Idiots",
    "description":"The film 3 Idiots drew inspiration from the real life story of an engineer-cum-scientist called Sonam Wangchuk. He is the founder of Student Educational and Cultural Movement in Ladakh that was established in the 1988 by the group of students.",
    "category": "Bollywood",
    "date":"December 04 2009",
    "likes":"100",
    "details":"In college, Farhan and Raju form a great bond with Rancho due to his positive and refreshing outlook to life. Years later, a bet gives them a chance to look for their long-lost friend whose existence seems rather elusive.The film 3 Idiots drew inspiration from the real life story of an engineer-cum-scientist called Sonam Wangchuk. He is the founder of Student Educational and Cultural Movement in Ladakh that was established in the 1988 by the group of students.Rupa & Co. Five Point Someone: What not to do at IIT is a 2004 novel written by Indian author Chetan Bhagat. The book sold over a million copies worldwide. The films 3 Idiots and Nanban are based on the book.The moral lesson of the movie 3 Idiots is Don t run behind the success Dont run behind the success, achieve excellence first, the success will automatically come looking for you. Creativity Be always creative in your answers, work & things you do which helps you become more capable of your own. ",
    "detailsimage":"https://wallpapercave.com/wp/wp6568176.jpg",
},
{
    "Id": "14",
    "imageurl":"https://pbs.twimg.com/media/EnRY0A7VEAANJgT.jpg",
    "title":"RRR",
    "description":"RRR is an upcoming Indian Telugu-language period action drama film directed by S. S. Rajamouli, and produced by D. V. V. Danayya of DVV Entertainments.",
    "category": "Bollywood",
    "date":"December 04 2021",
    "likes":"10",
    "details":"A tale of two legendary revolutionaries and their journey far away from home. After their journey they return home to start fighting back against British colonialists in the 1920s.The movie would be releasing in India in five languages being Telugu, Hindi, Tamil, Malayalam, and Kannada.The full form of RRR is “Roudram Ranam Rudhiram” in Telugu, “Raththam Ranam Rowthiram” in Tamil, “Roudra Rana Rudhira” in Kannada, “Rudhiram Ranam Roudhram” in Malayalam all of which means Rage War Blood. In English RRR stands for “Rise Roar Revolt”. ... RRR movie will feature Tollywood actors N. T. Rama Rao and Jr. ",
    "detailsimage":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwhkjwiTB7hycG6vURo_JBbTgwZximgTYyEw&usqp=CAU",
},
{
    "Id": "15",
    "imageurl":"https://images.indianexpress.com/2016/09/ms-dhoni-review-759.jpg",
    "title":"M.S. Dhoni",
    "description":"The Untold Story is a 2016 Indian Hindi-language biographical sports drama film written and directed by Neeraj Pandey. It is based on the life of M.S.Dhoni",
    "category": "Bollywood",
    "date":"August 04 2016",
    "likes":"100",
    "details":"M S Dhoni, a boy from Ranchi, aspires to play cricket for India. Though he initially tries to please his father by working for the Indian Railways, he ultimately decides to chase his dreams.Movie is based on real life struggle of Indian cricketer MS Dhoni.It was only when the former India captain's biopic MS Dhoni: The Untold Story came that the fans got to know about Priyanka Jha, the iconic cricketer's ex-girlfriend who had passed away in an accident. In the movie, it was actress Disha Patani who played the role of Priyanka. ",
    "detailsimage":"https://www.cricketcountry.com/wp-content/uploads/2016/09/Untitled14.png",
},  
{
    "Id": "16",
    "imageurl":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR32sstQYSwIKMf0-Zn8RVxrtQxUmL3yt2IGg&usqp=CAU",
    "title":"Harry Potter",
    "description":"Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry ",
    "category": "Hollywood",
    "date":"July 04 2007",
    "likes":"100",
    "details":"Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry.Harry's fear of Dementors is deeply significant. Dementors are a metaphor for the deep, inescapable spiral of depression and hopelessness. Harry fears losing every happy memory and being left with only the worst parts of himself — loss, death, and sorrow. This also happens to be my worst fear.While no, there is no actual Harry Potter, he was based on a real person! JK Rowling drew her inspiration for The Boy Who Lived from her neighbor Ian Potter who lived just four doors down from Rowling when she was a child.In the epilogue to Harry Potter and the Deathly Hallows, which is set 19 years later, it's revealed that Harry married Ginny Weasley, Ron's sister, and they have three children. Ron and Hermione have two kids together. ",
    "detailsimage":"https://m.media-amazon.com/images/I/51vCxEdIr4L._AC_SX450_.jpg",
}, 
{
    "Id": "17",
    "imageurl":"https://wallpaperaccess.com/full/4383611.jpg",
    "title":"Just Add Magic",
    "description":" Kelly Quinn and her two best friends, Darbie and Hannah, find Kelly's grandmother's cookbook in the attic and discover some strange recipes. They soon begin to realise they have a recipe book full of magic recipes.",
    "category": "Hollywood",
    "date":"August 04 2016",
    "likes":"100",
    "details":"Just Add Magic is an American live-action family television series, loosely based on the book of the same name by Cindy Callaghan. Kelly Quinn and her two best friends, Darbie and Hannah, find Kelly's grandmother's cookbook in the attic and discover some strange recipes. They soon begin to realise they have a recipe book full of magic recipes. ",
    "detailsimage":"https://images-na.ssl-images-amazon.com/images/I/71Ukie5QHwL.jpg",
},
{
    "Id": "18",
    "imageurl":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsK7EP4gIoQhNlX_7iW8y2dLyMlBQUtDMEN7V3jEXH7zVZShqVOLl50jHoWaYtHP5HjMY&usqp=CAU",
    "title":"Friends",
    "description":"Friends is an American television sitcom created by David Crane and Marta Kauffman, which aired on NBC from September 22, 1994, to May 6, 2004 ",
    "category": "Hollywood",
    "date":"August 04 2004",
    "likes":"10",
    "details":"Friends is an American television sitcom created by David Crane and Marta Kauffman, which aired on NBC from September 22, 1994, to May 6, 2004Follow the lives of six reckless adults living in Manhattan, as they indulge in adventures which make their lives both troublesome and happening.Ross Geller, Rachel Green, Monica Geller, Joey Tribbiani, Chandler Bing, and Phoebe Buffay are six twenty-somethings living in New York City.Kauffman and Crane began developing Friends under the working title Insomnia Cafe between November and December 1993. They presented the idea to Bright, and together they pitched a seven-page treatment of the show to NBC. After several script rewrites and changes, including title changes to Six of One[2] and Friends Like Us, the series was finally named Friends.[3]Filming took place at Warner Bros. Studios in Burbank, California. The entire series ranked within the top ten of the final television season ratings; it ultimately reached the number-one spot in its eighth season. The series finale aired on May 6, 2004, and was watched by around 52.5 million American viewers, making it the fifth-most-watched series finale in television history[4][5][6] and the most-watched television episode of the 2000s.[7][8] ",
    "detailsimage":"https://images.tbs.com/tbs/$dyna_params/https%3A%2F%2Fi.cdn.tbs.com%2Fassets%2Fimages%2F2019%2F08%2FFriends-Vizio-960x1440.png",
},
{
    "Id": "19",
    "imageurl":"https://upload.wikimedia.org/wikipedia/commons/f/f4/Wuling_Hongguang_Mini_EV_Macaron_001.jpg",
    "title":"Electric Vehicles",
    "description":"All-electric vehicles (EVs), also referred to as battery electric vehicles, are vehicles known to have an electric motor instead of the usual internal combustion engine vehicles we have been used to all our lives. ",
    "category": "Technology",
    "date":"August 04 2016",
    "likes":"100",
    "details":"All-electric vehicles (EVs), also referred to as battery electric vehicles, are vehicles known to have an electric motor instead of the usual internal combustion engine vehicles we have been used to all our lives. This vehicle is powered by a large traction battery pack that must be charged or plugged into a wall outlet. In the Republic of China, while new electric vehicle manufacturers are trying to get market share, 2 major manufacturers brands have stood out and remain market leaders. These manufacturers are Tesla and BYD according to the China Passenger Car Association.After years of growth, China’s vehicle demand began declining in 2019 and really nosedived especially in February 2020 as a result of the effect of the pandemic. Despite the unquantifiable effect of the pandemic, China remains the leading global auto market with an enormous amount of sales reported. Given the country’s population level, the potential for China’s automobile market is still presented as enormous. This huge market accounts for a growing 31.1% of all sales at a global level.The US is second on the list, followed by Japan and then India. In 5th place is Germany, followed by Brazil followed by South Korea, then Russia,  At the edge of the top 10 rankings, we find France and finally the United Kingdom. All this makes up the top 10 auto markets in the world. With a focus on China, we present to you the top 10 best-selling new energy passenger cars, including SUVs, in the world’s largest auto market for the year 2021.1. Hongguang Mini EV is a battery-electric micro-car manufactured by SAIC-GM-Wuling since 2020. Retail deliveries began in China in July 2020. As of September 2021, sales since inception totalled 400,000 units.2. BYD Qin (pronounced “Chin”) is a compact sedan developed by BYD Auto, available as an all-electric car, as a plug-in hybrid and as an internal combustion engine vehicle.3. Tesla Model Y is an electric compact utility vehicle (CUV) manufactured by Tesla. This super EV was unveiled in March 2019, started production in January 2020, while deliveries started in March 2020.4. Tesla Model 3 is an electric fastback compact four-door sedan built by Tesla. The base Model 3 delivers an EPA-rated all-electric range of 272 miles (438 km) and the Long Range version delivers 358 miles (576 km). According to Tesla, this vehicle carries full self-driving hardware, with periodic software updates adding functionality. ",
    "detailsimage":"https://i0.wp.com/www.ccarprice.com/products/Tesla_Model_Y_Long_Range_2021_Price_Specs.jpg?resize=835%2C450&ssl=1",
},
{
    "Id": "20",
    "imageurl":"https://i0.wp.com/techbooky.com/wp-content/uploads/2021/12/jameswebb.jpg?w=940&ssl=1",
    "title":"NASA’s James Webb Telescope",
    "description":"The National Aeronautics and Space Administration (NASA) had a previous flagship product (The Hubble Telescope) whose potency has left many in awe but its latest addition; the James Webb Space Telescope (JWST) may as well leave us spell-bound as it’s more than 100 times potent than its predecessor. ",
    "category": "Technology",
    "date":"August 04 2016",
    "likes":"10",
    "details":"The National Aeronautics and Space Administration (NASA) had a previous flagship product (The Hubble Telescope) whose potency has left many in awe but its latest addition; the James Webb Space Telescope (JWST) may as well leave us spell-bound as it’s more than 100 times potent than its predecessor.After about 31 years of Space exploration with the Hubble Telescope, NASA has launched a new flagship in the orbit, the JWST, a flagship as large the size of a tennis court, while being shaped like a spaceship out of Star Wars.The JWST, having eclipsed its forerunner, the Hubble, can reveal in meticulous detail, galaxies just as they existed 13.5 billion years ago, at the very inception of the universe.The old Telescope by NASA, Hubble was designed in such a way that it would capture only visible light, something humans can see with the normal eye. It allowed us gaze far into the universe, made us understand planet formation, gave us the opportunity to know the age of the universe but that may appear obsolete soon with the launch of a newer and more potent flagship.Hubble has since 1990; 31 years ago taken more than 1.5 million photos that may have helped shape our understanding of the universe as far as we can see it,  but JWST is far more effective with its ability to see in infrared, see past gas and dust clouds that float throughout space. ",
    "detailsimage":"https://i0.wp.com/techbooky.com/wp-content/uploads/2021/12/jameswebb.jpg?w=940&ssl=1",
},
{
    "Id": "21",
    "imageurl":"https://www.thenationalnews.com/resizer/zCauE_YvgG4F-4o879hrWGIKRxg=/arc-photo-thenational/eu-central-1-prod/public/3I7VZRIVX7R5M2SQSPLEBK7AR4.jpg",
    "title":"Sophia-The Robot",
    "description":"Sophia is a social humanoid robot developed by the Hong Kong-based company Hanson Robotics. Sophia was activated on February 14, 2016.   ",
    "category": "Technology",
    "date":"February 14 2016",
    "likes":"100",
    "details":"Sophia is a social humanoid robot developed by the Hong Kong-based company Hanson Robotics. Sophia was activated on February 14, 2016, and made her first public appearance in mid-March 2016 at South by Southwest in Austin, Texas, United States. A Little Sophia costs between $99 and $149, depending on when it's ordered, and Hanson expects to deliver the bots in December 2019.The robot's internal architecture possesses sophisticated software, chat and artificial intelligence systems designed for general reasoning. Sophia is capable of imitating human gestures and facial expressions. ... The robot is designed to get smarter over time.Ben Goertzel is a brilliant full-stack AI researcher and the chief scientist and chairman of AI software company Novamente LLC; chairman of the OpenCog Foundation; and advisor to Singularity University. He was formerly Chief Scientist of Hanson Robotics, the company that created Sophia.Honda Motor Corporation's Asimo, with its humanoid appearance and ability to walk and climb stairs, has been dubbed the world's most advanced robot. ",
    "detailsimage":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxbItTNhp2VU1dOp0CBVo2_54ljUhPiOe6Yg&usqp=CAU",
},
{
    "Id": "22",
    "imageurl":"https://www.southtourism.in/assets/images/araku-valley-city.jpg",
    "title":"Araku Valley",
    "description":"Araku Valley is a hill station and valley region in the southeastern Indian state of Andhra Pradesh. It's surrounded by the thick forests of the Eastern Ghats mountain range. ",
    "category": "Travel",
    "date":"August 04 2016",
    "likes":"100",
    "details":"A place of immense scenic beauty, Araku valley is a must visit tourist destination for every nature lover.Araku Valley is a hill station and valley region in the southeastern Indian state of Andhra Pradesh. It's surrounded by the thick forests of the Eastern Ghats mountain range. The Tribal Museum is dedicated to the area's numerous indigenous tribes, known for their traditional Dhimsa dance, and showcases traditional handicrafts. A miniature train runs through Padmapuram Gardens, with its sculptures and tree-top huts.Araku Valley - The Hill Station Of Andhra Pradesh. ... The Galikonda hill has the distinction of being the tallest hill in the state of Andhra Pradesh. Apart from being a beautiful hill station, Araku Valley is also famous for its rich coffee plantations. The aroma of fresh coffee beans is in the air of Araku throughout.The best time to visit Araku Valley is in the winter from December to February. The Valley is doubly enchanting amid the magic of the winter air. With pleasant days and cool nights, all sightseeing activities are best done during this time of the year.Located at an altitude of 4,590 feet, Araku Valley, also known as the Ooty of A.P., is a three-hour drive from Vizag. It is a variegated valley with lofty mountains, deep jungles, waterfalls and twirling streams.The journey to Araku valley is most enjoyable when you travel by both rail and road, according to the Andhra Pradesh Tourism Department. from Visakhapatnam. While the road, covered by thick jungle on both sides, snakes through the Anantagiri range, the rail takes you through 58 tunnels and over 84 bridges. ",
    "detailsimage":"https://www.wtravelmagazine.com/wp-content/uploads/2017/06/15_19_a-Waterfalls-at-Maharashtra-India-by-Snehal-Jeevan-Pailkar.jpg",
},
{
    "Id": "23",
    "imageurl":"https://mykurnool.online/wp-content/uploads/2020/11/konda-reddy-Burju.jpg",
    "title":"Konda Reddy Fort",
    "description":"Konda Reddy Fort, also known as Kondareddy Buruju is a fort situated in the city of Kurnool in Andhra Pradesh, India. At a distance of 2 km from Kurnool ",
    "category": "Travel",
    "date":"January 04 2020",
    "likes":"70",
    "details":"Konda Reddy Fort, also known as Kondareddy Buruju is a fort situated in the city of Kurnool in Andhra Pradesh, India. At a distance of 2 km from Kurnool.Konda Reddy Fort, also known as Kondareddy Buruju is a fort situated in the city of Kurnool in Andhra Pradesh, India. At a distance of 2 km from Kurnool Railway Station and 24 km from Alampur, Konda Reddy Buruju is an imposing structure situated in the heart of Kurnool City. ",
    "detailsimage":"https://thumbs.dreamstime.com/b/konda-reddy-fort-also-known-as-kondareddy-buruju-kurnool-andhra-pradesh-konda-reddy-fort-also-known-as-kondareddy-buruju-kurnool-231306988.jpg",
},
{
    "Id": "24",
    "imageurl":"https://dc-cdn.s3-ap-southeast-1.amazonaws.com/dc-Cover-3qgtv90a7shtmk4qgforq4c5j0-20160908070350.Medi.jpeg",
    "title":"ISRO",
    "description":"The Indian Space Research Organisation is the national space agency of India, headquartered in Bengaluru. It operates under the Department of Space which is directly overseen by the Prime Minister of India, while Chairman of ISRO acts as executive of DOS as well. ",
    "category": "Travel",
    "date":"August 04 2016",
    "likes":"100",
    "details":"The Indian Space Research Organisation is the national space agency of India, headquartered in Bengaluru. It operates under the Department of Space which is directly overseen by the Prime Minister of India, while Chairman of ISRO acts as executive of DOS as well.Satish Dhawan Space Centre (SDSC) or Sriharikota Range (SHAR) is a rocket launch centre (spaceport) operated by Indian Space Research Organisation (ISRO).The Secretariat of DOS and ISRO Headquarters are located at Antariksh Bhavan in Bangalore.Sriharikota is a barrier island in the Andhra Pradesh state of India. It is most famous as the home of India's only satellite launch center.Engineering Tourism - Sri Potti Sriramulu Nellore District-This state of the art facility is maintained by Indian Space Research Organization (ISRO) and is the main base for India's space flight programs. ",
    "detailsimage":"https://www.isro.gov.in/sites/default/files/Satish%20Dhawan%20Space%20Centre%20(SDSC)%20SHAR/mcc_shar.jpg",
},
{
    "Id": "25",
    "imageurl":"https://image.shutterstock.com/image-photo/belum-caves-andhra-pradesh-india-600w-1469446121.jpg",
    "title":"Belum Caves",
    "description":"The Belum Caves is the largest and longest cave system open to the public on the Indian subcontinent, known for its speleothems, such as stalactite and stalagmite formations. The Belum Caves have long passages, galleries, spacious caverns with fresh water and siphons. ",
    "category": "Travel",
    "date":"August 04 2016",
    "likes":"10",
    "details":"The Belum Caves is the largest and longest cave system open to the public on the Indian subcontinent, known for its speleothems, such as stalactite and stalagmite formations. The Belum Caves have long passages, galleries, spacious caverns with fresh water and siphons.Formation: The cave is more than a thousand year old, and was formed by the constant flow of underground water over a period of time.Belum Caves, also known as Belum Guhalu in Andhra Pradesh is the second longest cave in the Indian subcontinent open to public. ... These caves are renowned for their speleothem structures, such as stalactite and stalagmite formations.Belum Caves derives its name from Bilum Sanskrit word for caves. In Telugu language, it is called Belum Guhalu. Belum Caves has a length of 3229 meters, making it the second largest natural caves in Indian Subcontinent. Belum Caves have long passages, spacious chambers, fresh water galleries and siphons.Belum Caves has a length of 3229 meters, making it the second largest natural caves in Indian Subcontinent. discovered in 1884 by a British surveyor Robert Bruce Foote, later in 1982-84, a team of German speleologists headed by H Daniel Gebauer conducted a detailed exploration of the caves. ",
    "detailsimage":"https://static.toiimg.com/thumb/66525251/Belum-cave.jpg?width=1200&height=900",
},
{
    "Id": "26",
    "imageurl":"https://miro.medium.com/max/1200/1*eozEMMU0c8zss8y9d5iH-Q.jpeg",
    "title":"Masala Dosa",
    "description":"South India’s most renowned culinary export, masala dosas are famous the world over. ",
    "category": "Food",
    "date":"August 04 2016",
    "likes":"100",
    "details":"Arguably South India’s most renowned culinary export, masala dosas are famous the world over. A sort of Indian pancake, dosas are made from a thin batter consisting of rice, flour and lentils. Making dosas is no easy task, with the batter mixture having to soak in water for at least 24 hours before it can be shaped. Once ready, the batter is ladled onto a hot tava (griddle pan) and shaped in a similar way to how the French would shape a crepe. Traditionally, dosas are served folded in half and stuffed with potatoes. Accompaniments like hot sambar give the dish a spicy edge, and whatever you stuff them with, dosas are sure to provide a tasty yet satisfying meal.Dosa has an interesting origin. It was called dosha meaning sin Deprived of alcohol, some brahmin temple cooks thought they could get high on fermented rice.Dosa/Dosai is being made for the past 2000 years and has originated from South India! The original Tamil Dosa was softer and thicker. The thinner and crispier version of Dosa, which is popular all over India, was first made in Karnataka. The Dosa is considered to be healthy.– Dosa or dosai or dose is one of the most regularly consumed crepes in South India. These are made in so many ways, each differ in proportions of lentils, rice and beaten rice used. ... The most commonly made in most homes is the plain dosa also called as sada or khali dose as we call it at home.medium dosa (97g )Calories from Fat 33. Calories 168.6% Total Fat 3.7g.3% Saturated Fat 0.5g.0% Cholesterol 0mg.4% Sodium 94mg.",
    "detailsimage":"https://miro.medium.com/max/1200/1*eozEMMU0c8zss8y9d5iH-Q.jpeg",
},
{
    "Id": "27",
    "imageurl":"https://carameltintedlife.com/wp-content/uploads/2021/01/Masala-Chai-.jpg",
    "title":"Masala Chai",
    "description":"India’s most famous export, masala chai can be found being sold by everywhere from high end restaurants to chaiwallas at train stations. ",
    "category": "Food",
    "date":"August 04 2016",
    "likes":"100",
    "details":"India’s most famous export, masala chai can be found being sold by everywhere from high end restaurants to chaiwallas at train stations.While there’s many different diluted versions of this classic Indian tea around the globe, the real deal can only be found in India. Authentic masala chai is made by brewing black tea on the stove with a mixture of aromatic spices and herbs. Traditionally, the spices used are green cardamom pods, cinnamon sticks, ground cloves and black pepper, creating a wonderful aromatic cup of tea. There’s nothing quite like sipping a hot cup of authentic masala chai first thing in the morning!  ",
    "detailsimage":"https://static.toiimg.com/thumb/84340119.cms?imgsize=207643&width=800&height=800",
},
{
    "Id": "28",
    "imageurl":"https://www.jacadatravel.com/wp-content/uploads/fly-images/316525/iStock-1177589252-552x310-cc.jpg",
    "title":"Pani puri",
    "description":"Pani puri, or gol guppa,  are thought to originate from the northern state of Bihar. ",
    "category": "Food",
    "date":"May 04 2005",
    "likes":"10",
    "details":"Pani puri, or gol guppa,  are thought to originate from the northern state of Bihar.A perfect streetside snack, pani puri are hollow deep fried balls made of semolina or wheat. They’re served alongside spicy potatoes, chickpeas and a spicy tamarind water. Eating pani puri is an experience in itself, as you traditionally crack open the top of the deep fried shell with a spoon before filling it with the delicious accompaniments. Most Indians eat each pani puri with one swift bite, to save any of the filling spilling out of the delicate case. This infamous street snack unites most of the country – everyone from local college students to city businessmen can be found devouring them. ",
    "detailsimage":"https://www.jacadatravel.com/wp-content/uploads/fly-images/316525/iStock-1177589252-552x310-cc.jpg",
},
{
    "Id": "29",
    "imageurl":"https://1.bp.blogspot.com/-B-RnWpLsXp0/XabGbINp95I/AAAAAAAA1Js/C76piodWLcsbe1gSC0NwDHI9cake1MPRwCLcBGAsYHQ/s1600/MilkSweet.jpg",
    "title":"Sweet Kova",
    "description":"Palkova is traditional milk sweet enriched with the richness of pure milk and is usually served in a thick manner. Sugar is the only sweet ingredient added to it. This delicious traditional South Indian Sweet is quite easy to prepare and moreover, the recipe requires just a few ingredients. ",
    "category": "Food",
    "date":"June 04 2018",
    "likes":"10",
    "details":"Palkova is traditional milk sweet enriched with the richness of pure milk and is usually served in a thick manner. Sugar is the only sweet ingredient added to it. This delicious traditional South Indian Sweet is quite easy to prepare and moreover, the recipe requires just a few ingredients.Palkova is basically an Indian sweet made by simmering milk until it reduces to about half of its original quantity. An utterly delicious sweet made from milk and sugar. Palkova is an amazing sweet for kids. It offers rich source of calcium and essential for healthy bones and teeth. It has vitamin D which is also beneficial for bone health. Our Palkova is a milk based sweet which is enriched with pure milk.We never forget to lend much more varieties of sweets for your sugary hunger. The recipe of this Palkova can never be compromised.It is obviously a milk product which is made up of heating raw milk at apt temperature. The unique specialty of this Palkova is depicted like, Soft and Yummy.Lending such milky sweet will also lend lot of happiness in your home. We all consider sweet is the first thing that has to touch our tongue before we proceed with any chore.We assure you, Palkova will make you mouth watering when you have a look on this. No more wait. ",
    "detailsimage":"https://shreemsweetsandbakery.com/wp-content/uploads/2020/11/milk-kova-600x600.jpg",
},
{
    "Id": "30",
    "imageurl":"https://variety.com/wp-content/uploads/2022/01/MCDJULE_EC046.jpg?w=681&h=383&crop=1",
    "title":"Batman",
    "description":"One of the most iconic fictional characters in the world, Batman has dedicated his life to an endless crusade, a war on all criminals in the name ",
    "category": "Hollywood",
    "date":"March 04 2017",
    "likes":"10",
    "details":"Batman is a superhero who appears in American comic books published by DC Comics. The character was created by artist Bob Kane and writer Bill Finger, and debuted in the 27th issue of the comic book Detective Comics on March 30, 1939.The 1960s Batman television series used a camp aesthetic, which continued to be associated with the character for years after the show ended. Various creators worked to return the character to his darker roots in the 1970s and 1980s, culminating with the 1986 miniseries The Dark Knight Returns by Frank Miller.Even after Bruce Wayne's return, Dick Grayson remained the star of this title through its final year, as well as being the main character in Batman and Robin and Detective Comics. Bruce Wayne starred in two new titles, Batman Incorporated and Batman: The Dark Knight.The Joker debuted in Batman #1 (April 1940) as the eponymous character's first villain, about a year after Batman's debut in Detective Comics #27 (May 1939).He is popular because he does what he does without any superpowers. This gives his readers, viewers, players, and other fans hope that with enough training and money, they could do what he does. And you're missing the appeal of the gadgets.Bruce Wayne Batman is super intelligent. ... Batman is the man of principles till he is alive he never lets anything go injustice in front of him he chooses his symbol of a bat because it was his fear but he overcame his fear and that what makes it much more interesting he makes his fear into every criminal's nightmare. ",
    "detailsimage":"https://variety.com/wp-content/uploads/2022/01/MCDJULE_EC046.jpg?w=681&h=383&crop=1",
},
{
    "Id":"31",
    "imageurl":"https://bsmedia.business-standard.com/_media/bs/img/article/2020-12/21/full/1608491852-3708.jpg",
    "title":"5G",
    "description":"In telecommunications, 5G is the fifth generation technology standard for broadband cellular networks, which cellular phone companies began deploying worldwide in 2019",
    "category":"Technology",
    "date":"November 10 2020",
    "likes":"10",
    "details":"In telecommunications, 5G is the fifth generation technology standard for broadband cellular networks, which cellular phone companies began deploying worldwide in 2019.and is the planned successor to the 4G networks which provide connectivity to most current cellphones.Wireless communications systems use radio frequencies (also known as spectrum) to carry information through the air. 5G operates in the same way, but uses higher radio frequencies that are less cluttered. This allows for it to carry more information at a much faster rate.5G is nowadays present in 30% of world nations, with a, roughly speaking, equal distribution across the 3 main world zones: Americas, Asia and EMEA (Europe, Middle East and Africa). At the head of the table of nations with the most 5G networks is China, followed by the USA and South Korea.5G is not only important because it has the potential to support millions of devices at ultrafast speeds, but also because it has the potential to transform the lives of people around the world. ... Access to 5G technology promises to improve mission-critical services that affect safety and security of services today.The main disadvantage of 5G is that it has limited global coverage and is available only in specific locations. Only cities can benefit a lot from 5G network and remote areas may not get the coverage it for some years. Moreover, the expenses for setting tower stations are high when compared to other networks.",
    "detailsimage":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9c_cpWkqTlIKjaTVBngI5nEL61jntQsjwfQ&usqp=CAU",
},
])
        return (
            <Createcontext.Provider value={[data,setData]}>
                {props.children}
            </Createcontext.Provider>
        )
    }